version: '3'
services:
  postgres:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
